# Author: Matéo Millet

name: Azure Static Web App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - qa

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Enable Corepack & Install dependencies
        run: |
          corepack enable
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build the application
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    name: Deploy to Azure Static Web Apps on prod or qa
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy to Azure
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            swa deploy ./dist --app-name "${{ secrets.AZURE_PROD_APP_NAME }}" --env production --deployment-token "${{ secrets.AZURE_PROD_APP_TOKEN }}"
          else
            swa deploy ./dist --app-name "${{ secrets.AZURE_QA_APP_NAME }}" --env qa --deployment-token "${{ secrets.AZURE_QA_APP_TOKEN }}"
          fi
