# Author: Matéo Millet

name: CI

on:
  push:
    branches: [main]
    paths-ignore: # Ignore changes in docs folder
      - "docs/**"
  pull_request:
    paths-ignore: # Ignore changes in docs folder
      - "docs/**"
  workflow_dispatch:
    inputs: # Let choose to run static analysis or not
      run_static_analysis:
        description: "Run static analysis?"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]
  schedule:
    - cron: "0 8 * * 1" # Auto-run : every monday at 08:00 UTC

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Enable Corepack and Install deps
        run: |
          corepack enable
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build the app
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/
          retention-days: ${{ github.ref == 'refs/heads/main' && 7 || 1 }}
          # Retention days for main branch is 7 days, otherwise 1 day

  quality-checks:
    name: Type-Check, Lint, Tests
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'schedule') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_static_analysis == 'true')

    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Enable Corepack & Install deps
        run: |
          corepack enable
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Type-Check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Run Tests
        run: pnpm test
